# Python numpy

In [3]:
'''
Lo primero es comprobar que tenemos instalado nmumpy y que lo podemos importar correctamente.
La ejecución de este bloque de código nos debe mostrar el array [1,2,3,4,5]
'''
import numpy as np

# Definición de un nuevo 'ndarray', de ahora en adelante lo llamaremos simplemente 'array'
test = np.array([1, 2, 3, 4, 5])
print(test)

[1 2 3 4 5]


In [ ]:
# Teoría
# aplicaciones numpy


### Primeros pasos

In [6]:
a= np.array([1,2,3,4,5,6])
print (a)
type(a)

[1 2 3 4 5 6]


numpy.ndarray

In [8]:
# definir un array de 2 dimensiones
b=np.array ([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
b=np.array([[1,2],[3,4],[5,6],[7,8]])
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
len ([[1,2],[3,4],[5,6],[7,8]])

4

In [19]:
#definir un array de 3 dimensiones (2,2,2)
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
#dimensiones de un array
print('dimensión: ',c.ndim)
print('dimension: ', a.ndim)
print('dimension: ', b.ndim)

dimensión:  3
dimension:  1
dimension:  2


In [27]:
print ('shape c:' , c.shape)
print ('shape a:' , a.shape)
print ('shape b:' , b.shape)

shape c: (2, 2, 2)
shape a: (6,)
shape b: (4, 2)


In [29]:
print (a.dtype)

int32


In [30]:
a=np.array([1,2,3,4,5,6], dtype=np.int16)
print(a.dtype)

int16


In [37]:
print(a.itemsize)
print(b.itemsize)

2
4


In [35]:
#obtener el tamaño total de un array
print ('n elementos', a.size)
print ('tamaño de cada elemento', a.itemsize)
print ('tamaño total', a.size * a.itemsize)

n elementos 6
tamaño de cada elemento 2
tamaño total 12


In [33]:
c.size

8

In [39]:
#número de elementos que tiene un array
print ('elementos a:', a.size)
print ('elementos b:', b.size)
print ('elementos c:', c.size)

elementos a: 6
elementos b: 8
elementos c: 8


In [41]:
#otra forma de inicializar arrays
e= np.arange(10)
print (e)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
e2=np.arange(10,20)
print (e2)

[10 11 12 13 14 15 16 17 18 19]


In [44]:
e3=np.arange(10,50,5)
print(e3)

[10 15 20 25 30 35 40 45]


Ejercicios

In [27]:
'''
Define el array 'a' del 1 al 10
'''
a=np.arange(1,11)
'''
Imprime la dimension del array y el shape
'''
print(a)
print ('La forma de array a ', a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
La forma de array a  (10,)


In [32]:
''' 
Define de un array 'b' de dimensiones 2x3 a partir de listas anidadas
'''
b=np.array([[1,2,3],[4,5,6]])
print (b)
print ('La forma de array a ', b.shape)

[[1 2 3]
 [4 5 6]]
La forma de array a  (2, 3)


In [34]:
'''
Define un array 'c'  de dim 2x2x3 a partir de una lista de listas anidadas 
'''
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print ('La forma de array a ', c.shape)
'''
Imprime el número total de elementos del array y el shape
'''

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
La forma de array a  (2, 2, 3)


'\nImprime el número total de elementos del array y el shape\n'

## Accediendo y Modificando elementos de un array

In [46]:
a=np.array([7,6,3,8,1,6,9])
print(a)

[7 6 3 8 1 6 9]


In [48]:
#Elemento de la primera posicion
a[0]
#obtener el 8
print(a[3])

8


Obtener un elemento de un array

In [50]:
#Elemento de la primera posicion
a[0]
#obtener el 8
print(a[3])

8


In [53]:
#error fuera de rango
#print(a[16])
#indies negativos
print (a[-1])
#otros indices negativos
print(a[-3])

9
1


In [56]:
b= np.arange(1,15)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [57]:
#seleccion de rango de elementos
print(b[0:4])

[1 2 3 4]


In [59]:
print (b[5:15])

[ 6  7  8  9 10 11 12 13 14]


In [61]:
print(b[5:15:2])
print(b[15:0:-2])

[ 6  8 10 12 14]
[14 12 10  8  6  4  2]


In [62]:
#si no indica nada el inicio  es implicito
print(b[:10])

[ 1  2  3  4  5  6  7  8  9 10]


In [63]:
print (b[5:])

[ 6  7  8  9 10 11 12 13 14]


Obtener una fila completa de un array

In [64]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print (c)

[[1 2 3 4]
 [5 6 7 8]]


In [65]:
#obtener un elemento de 2d
print (c[1,1])

6


In [67]:
#obtener la segunda fila completa
print (c[1,:])

[5 6 7 8]


Obtener una columna completa de un array

In [68]:
print(c[:,2])

[3 7]


Otras formas de acceder a los elementos de un array

In [72]:
# elementos en posiciones pares de todas las filas
print (c[:, 0::2])
print (c[:, ::2])

[[1 3]
 [5 7]]
[[1 3]
 [5 7]]


In [73]:
d= np.arange(40).reshape(10,4)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


Actualizar un elemento de un array

In [75]:

e= np.arange(40).reshape(10,4)
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [3]:
e[0,0]=99

In [4]:
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [5]:
e[2,1]=0
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [6]:
e[-1,:]=0
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [ 0  0  0  0]]


In [7]:
e[-1,:]=[1,2,3,4]
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [ 1  2  3  4]]


In [8]:
e[-1,:]=e[4,:]
print(e)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  0 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [16 17 18 19]]


In [9]:
e[:,-1]=e[:,0]
print(e)

[[99  1  2 99]
 [ 4  5  6  4]
 [ 8  0 10  8]
 [12 13 14 12]
 [16 17 18 16]
 [20 21 22 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


In [11]:
e[4:6,1:3]=0
print (e)

[[99  1  2 99]
 [ 4  5  6  4]
 [ 8  0 10  8]
 [12 13 14 12]
 [16  0  0 16]
 [20  0  0 20]
 [24 25 26 24]
 [28 29 30 28]
 [32 33 34 32]
 [16 17 18 16]]


Ejercicios

In [37]:
'''
Define un array 's' de tamaño 10 y selecciona el valor de la posición 5
'''
s=np.arange(10)
print (e2)
print(e2[4])

[0 1 2 3 4 5 6 7 8 9]
4


In [38]:
'''
Sobre el array s, selecciona el valor 5
'''
print (e2)
print(e2[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [43]:
'''
Define el array 's' de tamaño 25 y selecciona los valores pares
'''
print(e2)
print(e2[::2])
print(e2[2::2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[2 4 6 8]


In [44]:
'''
Define el array 's' de tamaño 25 y selecciona los valores impares
'''
print(e2)
print(e2[1::2])


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [45]:
'''
Sobre el array s, selecciona el uĺltimo valor
'''
print(e2)
print(e2[-1])

[0 1 2 3 4 5 6 7 8 9]
9


In [57]:
"""
Define el array 's' de tamaño 20 e invierte el orden de los valores
"""
e3=np.arange(20)
print(e3)

print(e3[-1::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [63]:
'''
Define un array s2 multidimensional de tamaño 2x2 y selecciona el valor de la segunda fila y la segunda columna
'''
s2=np.array([[1,2],[3,4]])
print(s2)
print ('La forma de array: ', s2.shape)
print(s2[1,1])

[[1 2]
 [3 4]]
La forma de array:  (2, 2)
4


In [74]:
'''
Define el array:
[
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
]
y selecciona el valor de la segunda dimension, primera fila, segunda columna
'''
s3=np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print(s3)
print ('La forma de array: ', s3.shape)
print(s3[1,0,1])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
La forma de array:  (2, 2, 2)
6


In [94]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a 99
'''
s4= np.array ([[[1, 2,3], [4, 5,6],[7,8,9],[10,11,12]],[[13, 14,15], [16, 17,18],[19,20,22],[23,24,25]]])
print(s4)
print ('la forma es', s4.shape)
s4= np.array ([[[1, 2,3], [4, 5,6],[7,8,9],[10,11,12]],[[13, 14,15], [16, 17,18],[19,20,22],[23,24,25]]])
print(s4)
print ('la forma es', s4.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 22]
  [23 24 25]]]
la forma es (2, 4, 3)


In [134]:
s5= np.array ([[[1,2,3],[4,5,6],[7,8,9],[9,10,11]],[[12,13,14],[15,16,17],[18,19,20],[21,22,23]],[[24,25,26],[27,28,29],[30,31,32],[33,34,35]],[[36,37,38],[39,40,41],[42,43,44],[45,46,47]]])
print(s5)
print ('la forma es', s5.shape)
print(s5[:,1,1:3])
s5[:,1:3,1]=99
print(s5)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
la forma es (4, 4, 3)
[[ 5  6]
 [16 17]
 [28 29]
 [40 41]]
[[[ 1  2  3]
  [ 4 99  6]
  [ 7 99  9]
  [ 9 10 11]]

 [[12 13 14]
  [15 99 17]
  [18 99 20]
  [21 22 23]]

 [[24 25 26]
  [27 99 29]
  [30 99 32]
  [33 34 35]]

 [[36 37 38]
  [39 99 41]
  [42 99 44]
  [45 46 47]]]


In [135]:
s6=np.random.randint(40,60, size=(4,4,3))
print(s6)
print ('la forma es', s6.shape)



[[[55 50 40]
  [44 49 53]
  [53 58 58]
  [42 42 53]]

 [[58 50 48]
  [49 45 51]
  [46 50 40]
  [42 53 59]]

 [[54 50 42]
  [46 54 46]
  [52 43 44]
  [44 52 52]]

 [[48 56 40]
  [57 47 43]
  [46 55 51]
  [49 58 43]]]
la forma es (4, 4, 3)


In [124]:
s5= s5.reshape(2,8,3)
print(s5)
print(s5.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
(2, 8, 3)


In [4]:
'''
Define un array s4 de tamaño 4x4x3 y establece los números centrales a (0,1), (2,3), (4,5), (6,7)
'''
s7=np.random.randint(40,60, size=(4,4,3))

print ('la forma es', s7.shape)

s7[:1,1:2,1]=0
s7[:1,2:3,1]=1
s7[1:2,1:2,1]=2
s7[1:2,2:3,1]=3

s7[2:3,1:2,1]=4
s7[2:3,2:3,1]=5
s7[3:,1:2,1]=6
s7[3:,2:3,1]=7
print(s7)




la forma es (4, 4, 3)
[[[48 58 56]
  [43  0 47]
  [53  1 52]
  [42 53 43]]

 [[43 44 45]
  [47  2 52]
  [58  3 55]
  [42 41 43]]

 [[51 56 44]
  [42  4 49]
  [49  5 41]
  [45 56 49]]

 [[45 42 42]
  [47  6 55]
  [44  7 52]
  [56 45 59]]]


In [5]:
s7=np.random.randint(40,60, size=(4,4,3))

print ('la forma es', s7.shape)
s7[:,1:3,1]=[[0,1], [2,3], [4,5], [6,7]]
print(s7)

la forma es (4, 4, 3)
[[[47 40 59]
  [50  0 52]
  [47  1 55]
  [48 49 59]]

 [[55 53 51]
  [59  2 56]
  [56  3 46]
  [48 59 56]]

 [[55 56 43]
  [48  4 54]
  [40  5 40]
  [52 49 51]]

 [[57 52 43]
  [47  6 47]
  [44  7 40]
  [49 46 43]]]


In [8]:
s4 = np.arange(48).reshape(4,4,3)
s4[:,1:-1,1:-1] = np.arange(8).reshape(4,2,1)
print(s4) 

[[[ 0  1  2]
  [ 3  0  5]
  [ 6  1  8]
  [ 9 10 11]]

 [[12 13 14]
  [15  2 17]
  [18  3 20]
  [21 22 23]]

 [[24 25 26]
  [27  4 29]
  [30  5 32]
  [33 34 35]]

 [[36 37 38]
  [39  6 41]
  [42  7 44]
  [45 46 47]]]


In [11]:
s4 = np.arange(8).reshape(4,2,1)
print(s4)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]]


## Inicializando diferentes tipos de arrays

Matriz de ceros

In [13]:
#podemos inicializar con valor (1dimension o con shape para n dimensiones)
zeros= np.zeros((10,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Matriz de unos

In [14]:
ones=np.ones((10,5))
print (ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Matriz de valores concretos

In [15]:
valores=np.full((3,3), 99)
print (valores)

[[99 99 99]
 [99 99 99]
 [99 99 99]]


Matriz de valores concretos (full like)

In [16]:
full_like=np.full_like (ones,99)
print(full_like)

[[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]]


Matriz de números aleatorios

In [17]:
aleatorios =np.random.rand(20)
print(aleatorios)

[0.69933993 0.65890048 0.4364544  0.1895868  0.18539504 0.07731655
 0.18634096 0.90123792 0.35057783 0.60455985 0.4159217  0.47334178
 0.69046586 0.38433576 0.598135   0.66775083 0.95012909 0.14511316
 0.87165028 0.33950226]


In [18]:
f=np.random.rand(4,3)
print(f)

[[0.5141682  0.7129956  0.21024361]
 [0.79746371 0.65744467 0.33418694]
 [0.59743534 0.35116824 0.61937543]
 [0.96929213 0.63258492 0.89199477]]


In [20]:
g=np.random.randint(100,size=10)
print(g)

[ 2 39 57 23 45 19  0 34 37 73]


In [22]:
h= np.random.randint(50,100,size=(4,5))
print (h)

[[67 85 95 73 85]
 [84 50 61 68 92]
 [51 52 97 73 84]
 [88 98 65 85 68]]


In [ ]:
j= np.random.randint(40,50,size=(4,5))
print (j)

Matriz identidad

In [24]:
identidad=np.identity(9)
print(identidad)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Ejercicios

In [14]:
'''
Define el array z de dim 1 completo de ceros
'''
zeros= np.zeros((10))
print(zeros)
print(zeros.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)


In [15]:
'''
Define un array z de dim 8x8 completo de ceros
'''
zeros8= np.zeros((8,8))
print(zeros8)
print(zeros8.shape)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
(8, 8)


In [ ]:
'''
Define el array 'z' completo de ceros de n dim
'''

In [ ]:
'''
Define el array 'd' completo de unos de n dim
'''

In [ ]:
'''
Define un array como el que se muestra a continuación:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
'''

In [ ]:
'''
Define un array 'g' conun range de 0 a 10 de dim 2
'''

In [ ]:
'''
Define un array 'h' con un range de 0 a 100 con un paso de 5 y una dim difrente de 1
'''

## Operaciones con arrays

operaciones básicas

In [17]:
a = np.array([1, 2, 3, 4, 5])

In [18]:
#Listas python
#[1,2,3,4,5]
# ndarray numpy
a=np.array([1, 2, 3, 4, 5])
print(a+2)

[3 4 5 6 7]


In [20]:
b=np.array([6,7,8,9,10])
a = np.array([1, 2, 3, 4, 5])
a+b


array([ 7,  9, 11, 13, 15])

In [23]:
#2dimensiones
c= np.arange(9).reshape(3,3)
d=np.arange(9,18).reshape(3,3)
print('este es c',c)
print('este es d',d)
print('suma',c+d)

este es c [[0 1 2]
 [3 4 5]
 [6 7 8]]
este es d [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
suma [[ 9 11 13]
 [15 17 19]
 [21 23 25]]


In [26]:
#mutiplicacion matrices
c= np.arange(9).reshape(3,3)
d=np.arange(9,18).reshape(3,3)
print('este es c',c)
print('este es d',d)
print(np.matmul(c,d))
#otras formas:
print(c.dot(d))
print (c@d)

este es c [[0 1 2]
 [3 4 5]
 [6 7 8]]
este es d [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [30]:
#obterner la traspuesta de una matriz
e= np.arange(24).reshape(6,4)
print(e)
print ('esto es Traspuest',np.transpose(e))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
esto es Traspuest [[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


Ejercicios

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación suma los valores de ambos arrays y comprueba que los valores son correctos.
'''

In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 1s. A contunuación resta los valores de ambos arrays y comprueba que los valores son correctos.
'''


In [ ]:
'''
Define un array 'a' de tamaño 4 y un array 'b' de tamaño 4 completo de 2s. A contunuación multiplica o divide los valores de ambos arrays y comprueba que los valores son correctos.
'''

Álgebra lineal

Estadísticas

operaciones con arrays:
- **np.sum():** Suma de todos los elementos de un array
- **np.mean():** Media de todos los elementos de un array
- **np.std():** Desviación estándar de todos los elementos de un array
- **np.var():** Varianza de todos los elementos de un array
- **np.min():** Valor mínimo de todos los elementos de un array
- **np.max():** Valor máximo de todos los elementos de un array
- **np.flip():** Inversa de un array


In [31]:
a= np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [32]:
#sumatorio
sumatorio=np.sum(a)
sumatorio

276

In [35]:
#sumatorio de la primera fila
primera_fila=a[0,:]
sumatorio_primera_fila=np.sum(primera_fila)
sumatorio_primera_fila
#otra forma
print(np.sum(a[0,:]))

6


In [36]:
#promedio valores
promedio=np.mean(a)
promedio

11.5

In [38]:
#promedio primera fila
print(np.mean(a[:,0]))

10.0


In [40]:
#minimo valor d ela matriz
minimo=np.min(a)
print(minimo)
maximo=np.max(a)
print(maximo)

0
23


In [41]:
#maximo de una seccion del array
max_seccion=np.max(a[1:,:])
max_seccion

23

In [43]:
#seleccion 2d [fila ,columna]
print (a)
a[1:3, :]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
#flip 1d
a=np.arange(10)
print(a)
print(np.flip(a))

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [45]:
a=np.arange(24).reshape(6,4)
print(a,'\n')
print(np.flip(a))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[23 22 21 20]
 [19 18 17 16]
 [15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


## Reorganizando



In [49]:
#Reshape reorganiza el array con la forma indicada
a=np.random.rand(100).reshape(10,10)
print(a)
print(a.shape, '\n')



[[0.07913639 0.82858481 0.03135643 0.85920603 0.72707196 0.57233945
  0.97883589 0.67237766 0.90217243 0.02130626]
 [0.73970608 0.71147981 0.6717377  0.95327881 0.07796935 0.9131564
  0.00604703 0.90307174 0.63425833 0.76005243]
 [0.5911921  0.46527156 0.48510293 0.96148742 0.15615615 0.87356624
  0.4041773  0.71675    0.30494083 0.10999773]
 [0.64437906 0.5653055  0.51253287 0.66829338 0.48505038 0.33491234
  0.96818547 0.51501495 0.84264649 0.93109517]
 [0.13413595 0.99988427 0.56941391 0.03176712 0.31394271 0.77041148
  0.25526562 0.11623543 0.77481457 0.15666151]
 [0.81892202 0.07343063 0.39585819 0.62323323 0.30437278 0.48711445
  0.69968121 0.5182042  0.85449299 0.59130298]
 [0.45332999 0.71620673 0.90256948 0.73610847 0.35726941 0.89104071
  0.18767399 0.7149017  0.2177397  0.69568801]
 [0.49470697 0.70602597 0.04761831 0.95657318 0.5772005  0.37583483
  0.96339149 0.70806857 0.0516806  0.85058267]
 [0.90005257 0.60823296 0.06042406 0.49977455 0.96480463 0.28131756
  0.049294   

In [51]:
#Apilar un array
a=np.arange(5)
b=np.arange(6,11)
c=np.arange(11,6,-1)
np.vstack([c,a,b])

array([[11, 10,  9,  8,  7],
       [ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [53]:
#apilar arrays en 3d horizontal
a=np.arange(24).reshape(6,4)
b=np.arange(24,0,-1).reshape(6,4)
print(a,'\n')
print(b,'\n')
np.vstack([a,b])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[24 23 22 21]
 [20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]] 



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 23, 22, 21],
       [20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [55]:
#apilar arrays en 3d 
a=np.arange(24).reshape(6,4)
b=np.arange(24,0,-1).reshape(6,4)
print(a,'\n')
print('esto es b',b,'\n')
print (np.dstack([a,b]),'\n')
print (np.dstack([a,b]).shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

esto es b [[24 23 22 21]
 [20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]] 

[[[ 0 24]
  [ 1 23]
  [ 2 22]
  [ 3 21]]

 [[ 4 20]
  [ 5 19]
  [ 6 18]
  [ 7 17]]

 [[ 8 16]
  [ 9 15]
  [10 14]
  [11 13]]

 [[12 12]
  [13 11]
  [14 10]
  [15  9]]

 [[16  8]
  [17  7]
  [18  6]
  [19  5]]

 [[20  4]
  [21  3]
  [22  2]
  [23  1]]] 

(6, 4, 2)


In [56]:
#Concatenar en la 3d
print (np.array([a,b]))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 23 22 21]
  [20 19 18 17]
  [16 15 14 13]
  [12 11 10  9]
  [ 8  7  6  5]
  [ 4  3  2  1]]]


Cargar datos de un fichero

In [64]:
fichero=np.genfromtxt('numpy_values.txt', delimiter=',')
#print(fichero)
fichero=fichero.astype(int)
print(fichero)
print(type(fichero))
print(fichero.shape)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [41 12 43  6 45  8 47  1 49  1]]
<class 'numpy.ndarray'>
(5, 10)


Máscaras booleanas y operaciones avanzadas

In [63]:
#[True,True,False] generar una mascara booleana
#La mascara filtra los valores>40
mask=fichero>40
mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])

In [68]:
#aplica mascar booleana
print(fichero[mask],'\n')
#otra forma
print (fichero [fichero<40])

[41 43 45 47 49] 

[ 1  2 13  4 15  6 17  8 19 10 11  2 13  4  5 16  7 18  9 20 21 12 23  6
 25  8 27  1 29  1 31  2 33  4 35  6 37  8 39 10 12  6  8  1  1]


In [70]:
#poner a 0 los valores > 40
fichero[mask]=0
print(fichero)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [ 0 12  0  6  0  8  0  1  0  1]]


In [72]:
#concatenar condiciones
mayores_30_menores_40= (fichero>30) & (fichero<40)
print(mayores_30_menores_40)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [ True False  True False  True False  True False  True False]
 [False False False False False False False False False False]]


In [74]:
#Aplicar mascara concatenada condiciones
fichero[mayores_30_menores_40]

array([31, 33, 35, 37, 39])

In [75]:
#negar condiciones
no_ayores_30_no_menores_40= np.logical_not((fichero>30) & (fichero<40))
print(no_ayores_30_no_menores_40)

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [False  True False  True False  True False  True False  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [76]:
#Any
#hay algun valor mayor que 50?
np.any(fichero>50)

False

In [78]:
#any se puede especificar si la comprobacion es por filas o columnas con axis
#Obtener la columnas que contienen un valor >40
print(fichero)
colunma_mayores_40=np.any(fichero >40, axis=0)
print(colunma_mayores_40)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [ 0 12  0  6  0  8  0  1  0  1]]
[False False False False False False False False False False]


In [82]:
#aplicar


In [80]:
print(fichero)
colunma_mayores_40=np.any(fichero >40, axis=1)
print(colunma_mayores_40)

[[ 1  2 13  4 15  6 17  8 19 10]
 [11  2 13  4  5 16  7 18  9 20]
 [21 12 23  6 25  8 27  1 29  1]
 [31  2 33  4 35  6 37  8 39 10]
 [ 0 12  0  6  0  8  0  1  0  1]]
[False False False False False]
